# Generated by Django 3.0.3 on 2020-02-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decade',
            name='start_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fad',
            name='decade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fad',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fad',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
