# Generated by Django 3.0.3 on 2020-02-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_auto_20200228_2140'),
        ('nostaldja', '0002_auto_20200228_2139'),
    ]

    operations = [
    ]
